[package]
name = "cell_sim"
version = "0.0.1"
edition = "2021"
description = "A 1d cell automata simulator for the command line"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
