[package]
name = "cell_sim"
version = "0.0.2"
edition = "2021"
description = "A 1d cell automata simulator for the command line"
license = "MIT"

[dependencies]
clap = { version = "3.0.10", features = ["derive"] }
